library(readxl)
base <- read_excel('C:/Users/amand/OneDrive/Documentos/GitHub/laboratorio1/Respostas.xlsx')
base <- base[, -ncol(base)]
name_columns <- c(
  "genero",
  "outro",
  "idade",
  "estado_civil",
  "outro_estado_civil",
  "filhos",
  "qtd_filhos",
  "idade_filhos",
  "mora_com",
  "outro_mora_com",
  "escolaridade",
  "curso_formacao",
  "categoria",
  "cargo",
  "cargo_nivel1",
  "cargo_nivel2",
  "carga_horaria_semanal",
  "outro_carga_horaria_semanal",
  "unidade_lotacao",
  "cd_ou_fg",
  "campus",
  "ano_ingresso",
  "ingresso_cotas_pcd",
  "sentimento_local_trabalho",
  "deficiencia",
  "deficiencia_outro",
  "periodo_diagnostico",
  "causa_deficiencia",
  "uso_tecnologia_assistiva_recurso",
  "qual_tecnologia",
  "tecnologia_disponibilizada_ufsm",
  "como_consegue_obter_tecnologia",
  "voce necessita de algum acompanhamento ou apoio de outra pessoa para realizar as atividades cotidianas no ambiente de trabalho?",
  "se necessita, em quais atividades?",
  "esse acompanhamento/apoio e disponibilizado pela ufsm?",
  "se nao, como voce consegue obter?",
  "de um modo geral, como voce considera o nivel de acessibilidade arquitetonica da ufsm?",
  "de um modo geral, como voce considera o nivel de acessibilidade atitudinal da ufsm?",
  "de um modo geral, como voce considera o nivel de acessibilidade instrumental/digital da ufsm?",
  "de um modo geral, como voce considera o nivel de acessibilidade comunicacional da ufsm?",
  "voce conhece a legislacao brasileira sobre acessibilidade?",
  "qual seu objetivo quando fez o concurso para a ufsm?",
  "outro",
  "voce sentiu dificuldade de adaptacao durante o ingresso nas atividades laborais na ufsm?",
  "se sim, poderia relatar? como foi resolvido?",
  "voce enfrentou algum problema de relacionamento interpessoal com chefias e/ou colegas?",
  "se sim, poderia relatar? como foi resolvido?",
  "voce ja foi parte reclamante, na ufsm, em algum processo administrativo disciplinar (pad), sindicancia e/ou reclamatoria trabalhista?",
  "voce considera que a ufsm dispoe de recursos humanos e materiais suficientes para atender necessidades que possam eventualmente surgir relacionadas a acessibilidade?",
  "se nao, poderia relatar o que considera insuficiente?",
  "voce participa de alguma associacao, sindicato, ou outros grupos de luta por defesa de direitos trabalhistas?",
  "qual?",
  "se participa, voce sente que as pautas das pcd sao consideradas nas acoes dessa associacao/sindicato/grupo?",
  "espaco para outros comentarios e informacoes que voce queira nos passar sobre inclusao e acessibilidade na ufsm:"
)
